//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServiceApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class Licenciamiento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Licenciamiento()
        {
            this.Auditoria = new HashSet<Auditoria>();
        }
    
        public int NumeroLicencia { get; set; }
        public string NombreArchivo { get; set; }
        public string NombreCliente { get; set; }
        public string IdLicencia { get; set; }
        public string Version { get; set; }
        public string SerialModulos { get; set; }
        public string Concurrencia { get; set; }
        public Nullable<System.DateTime> FechaSolicitud { get; set; }
        public Nullable<System.DateTime> FechaGeneracion { get; set; }
        public Nullable<System.DateTime> FechaCaducidad { get; set; }
        public string ResponsableSolicitud { get; set; }
        public string ResponsableGeneracion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual HashSet<Auditoria> Auditoria { get; set; }
        public virtual Clientes Clientes { get; set; }
    }
}
