//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fomularios.ServiceReferenceWS {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Usuario", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Usuario : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdUsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Usuario1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContraseñaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CorreoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Fomularios.ServiceReferenceWS.Roles[] RolesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int IdUsuario {
            get {
                return this.IdUsuarioField;
            }
            set {
                if ((this.IdUsuarioField.Equals(value) != true)) {
                    this.IdUsuarioField = value;
                    this.RaisePropertyChanged("IdUsuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Usuario1 {
            get {
                return this.Usuario1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Usuario1Field, value) != true)) {
                    this.Usuario1Field = value;
                    this.RaisePropertyChanged("Usuario1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Contraseña {
            get {
                return this.ContraseñaField;
            }
            set {
                if ((object.ReferenceEquals(this.ContraseñaField, value) != true)) {
                    this.ContraseñaField = value;
                    this.RaisePropertyChanged("Contraseña");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Correo {
            get {
                return this.CorreoField;
            }
            set {
                if ((object.ReferenceEquals(this.CorreoField, value) != true)) {
                    this.CorreoField = value;
                    this.RaisePropertyChanged("Correo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public Fomularios.ServiceReferenceWS.Roles[] Roles {
            get {
                return this.RolesField;
            }
            set {
                if ((object.ReferenceEquals(this.RolesField, value) != true)) {
                    this.RolesField = value;
                    this.RaisePropertyChanged("Roles");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Roles", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Roles : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdRolField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Fomularios.ServiceReferenceWS.Usuario[] UsuarioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int IdRol {
            get {
                return this.IdRolField;
            }
            set {
                if ((this.IdRolField.Equals(value) != true)) {
                    this.IdRolField = value;
                    this.RaisePropertyChanged("IdRol");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public Fomularios.ServiceReferenceWS.Usuario[] Usuario {
            get {
                return this.UsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.UsuarioField, value) != true)) {
                    this.UsuarioField = value;
                    this.RaisePropertyChanged("Usuario");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Clientes", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Clientes : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CarpetaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Fomularios.ServiceReferenceWS.Licenciamiento[] LicenciamientoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Carpeta {
            get {
                return this.CarpetaField;
            }
            set {
                if ((object.ReferenceEquals(this.CarpetaField, value) != true)) {
                    this.CarpetaField = value;
                    this.RaisePropertyChanged("Carpeta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public Fomularios.ServiceReferenceWS.Licenciamiento[] Licenciamiento {
            get {
                return this.LicenciamientoField;
            }
            set {
                if ((object.ReferenceEquals(this.LicenciamientoField, value) != true)) {
                    this.LicenciamientoField = value;
                    this.RaisePropertyChanged("Licenciamiento");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Licenciamiento", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Licenciamiento : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int NumeroLicenciaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreArchivoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreClienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdLicenciaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VersionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SerialModulosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ConcurrenciaField;
        
        private System.Nullable<System.DateTime> FechaSolicitudField;
        
        private System.Nullable<System.DateTime> FechaGeneracionField;
        
        private System.Nullable<System.DateTime> FechaCaducidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResponsableSolicitudField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResponsableGeneracionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Fomularios.ServiceReferenceWS.Auditoria[] AuditoriaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Fomularios.ServiceReferenceWS.Clientes ClientesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int NumeroLicencia {
            get {
                return this.NumeroLicenciaField;
            }
            set {
                if ((this.NumeroLicenciaField.Equals(value) != true)) {
                    this.NumeroLicenciaField = value;
                    this.RaisePropertyChanged("NumeroLicencia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string NombreArchivo {
            get {
                return this.NombreArchivoField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreArchivoField, value) != true)) {
                    this.NombreArchivoField = value;
                    this.RaisePropertyChanged("NombreArchivo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string NombreCliente {
            get {
                return this.NombreClienteField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreClienteField, value) != true)) {
                    this.NombreClienteField = value;
                    this.RaisePropertyChanged("NombreCliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string IdLicencia {
            get {
                return this.IdLicenciaField;
            }
            set {
                if ((object.ReferenceEquals(this.IdLicenciaField, value) != true)) {
                    this.IdLicenciaField = value;
                    this.RaisePropertyChanged("IdLicencia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Version {
            get {
                return this.VersionField;
            }
            set {
                if ((object.ReferenceEquals(this.VersionField, value) != true)) {
                    this.VersionField = value;
                    this.RaisePropertyChanged("Version");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string SerialModulos {
            get {
                return this.SerialModulosField;
            }
            set {
                if ((object.ReferenceEquals(this.SerialModulosField, value) != true)) {
                    this.SerialModulosField = value;
                    this.RaisePropertyChanged("SerialModulos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Concurrencia {
            get {
                return this.ConcurrenciaField;
            }
            set {
                if ((object.ReferenceEquals(this.ConcurrenciaField, value) != true)) {
                    this.ConcurrenciaField = value;
                    this.RaisePropertyChanged("Concurrencia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public System.Nullable<System.DateTime> FechaSolicitud {
            get {
                return this.FechaSolicitudField;
            }
            set {
                if ((this.FechaSolicitudField.Equals(value) != true)) {
                    this.FechaSolicitudField = value;
                    this.RaisePropertyChanged("FechaSolicitud");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public System.Nullable<System.DateTime> FechaGeneracion {
            get {
                return this.FechaGeneracionField;
            }
            set {
                if ((this.FechaGeneracionField.Equals(value) != true)) {
                    this.FechaGeneracionField = value;
                    this.RaisePropertyChanged("FechaGeneracion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public System.Nullable<System.DateTime> FechaCaducidad {
            get {
                return this.FechaCaducidadField;
            }
            set {
                if ((this.FechaCaducidadField.Equals(value) != true)) {
                    this.FechaCaducidadField = value;
                    this.RaisePropertyChanged("FechaCaducidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string ResponsableSolicitud {
            get {
                return this.ResponsableSolicitudField;
            }
            set {
                if ((object.ReferenceEquals(this.ResponsableSolicitudField, value) != true)) {
                    this.ResponsableSolicitudField = value;
                    this.RaisePropertyChanged("ResponsableSolicitud");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string ResponsableGeneracion {
            get {
                return this.ResponsableGeneracionField;
            }
            set {
                if ((object.ReferenceEquals(this.ResponsableGeneracionField, value) != true)) {
                    this.ResponsableGeneracionField = value;
                    this.RaisePropertyChanged("ResponsableGeneracion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public Fomularios.ServiceReferenceWS.Auditoria[] Auditoria {
            get {
                return this.AuditoriaField;
            }
            set {
                if ((object.ReferenceEquals(this.AuditoriaField, value) != true)) {
                    this.AuditoriaField = value;
                    this.RaisePropertyChanged("Auditoria");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public Fomularios.ServiceReferenceWS.Clientes Clientes {
            get {
                return this.ClientesField;
            }
            set {
                if ((object.ReferenceEquals(this.ClientesField, value) != true)) {
                    this.ClientesField = value;
                    this.RaisePropertyChanged("Clientes");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Auditoria", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Auditoria : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdRegistroField;
        
        private System.Nullable<int> NumeroLicenciaField;
        
        private System.Nullable<System.DateTime> FechaField;
        
        private System.Nullable<int> IdUsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ObservacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Fomularios.ServiceReferenceWS.Usuario UsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Fomularios.ServiceReferenceWS.Licenciamiento LicenciamientoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int IdRegistro {
            get {
                return this.IdRegistroField;
            }
            set {
                if ((this.IdRegistroField.Equals(value) != true)) {
                    this.IdRegistroField = value;
                    this.RaisePropertyChanged("IdRegistro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<int> NumeroLicencia {
            get {
                return this.NumeroLicenciaField;
            }
            set {
                if ((this.NumeroLicenciaField.Equals(value) != true)) {
                    this.NumeroLicenciaField = value;
                    this.RaisePropertyChanged("NumeroLicencia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public System.Nullable<System.DateTime> Fecha {
            get {
                return this.FechaField;
            }
            set {
                if ((this.FechaField.Equals(value) != true)) {
                    this.FechaField = value;
                    this.RaisePropertyChanged("Fecha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.Nullable<int> IdUsuario {
            get {
                return this.IdUsuarioField;
            }
            set {
                if ((this.IdUsuarioField.Equals(value) != true)) {
                    this.IdUsuarioField = value;
                    this.RaisePropertyChanged("IdUsuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Observacion {
            get {
                return this.ObservacionField;
            }
            set {
                if ((object.ReferenceEquals(this.ObservacionField, value) != true)) {
                    this.ObservacionField = value;
                    this.RaisePropertyChanged("Observacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public Fomularios.ServiceReferenceWS.Usuario Usuario {
            get {
                return this.UsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.UsuarioField, value) != true)) {
                    this.UsuarioField = value;
                    this.RaisePropertyChanged("Usuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public Fomularios.ServiceReferenceWS.Licenciamiento Licenciamiento {
            get {
                return this.LicenciamientoField;
            }
            set {
                if ((object.ReferenceEquals(this.LicenciamientoField, value) != true)) {
                    this.LicenciamientoField = value;
                    this.RaisePropertyChanged("Licenciamiento");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Configuraciones", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Configuraciones : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClaveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ValorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Clave {
            get {
                return this.ClaveField;
            }
            set {
                if ((object.ReferenceEquals(this.ClaveField, value) != true)) {
                    this.ClaveField = value;
                    this.RaisePropertyChanged("Clave");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Valor {
            get {
                return this.ValorField;
            }
            set {
                if ((object.ReferenceEquals(this.ValorField, value) != true)) {
                    this.ValorField = value;
                    this.RaisePropertyChanged("Valor");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceWS.WebServiceSoap")]
    public interface WebServiceSoap {
        
        // CODEGEN: Generating message contract since element name nombre from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddUsuarios", ReplyAction="*")]
        Fomularios.ServiceReferenceWS.AddUsuariosResponse AddUsuarios(Fomularios.ServiceReferenceWS.AddUsuariosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddUsuarios", ReplyAction="*")]
        System.Threading.Tasks.Task<Fomularios.ServiceReferenceWS.AddUsuariosResponse> AddUsuariosAsync(Fomularios.ServiceReferenceWS.AddUsuariosRequest request);
        
        // CODEGEN: Generating message contract since element name nombre from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateUsuario", ReplyAction="*")]
        Fomularios.ServiceReferenceWS.UpdateUsuarioResponse UpdateUsuario(Fomularios.ServiceReferenceWS.UpdateUsuarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateUsuario", ReplyAction="*")]
        System.Threading.Tasks.Task<Fomularios.ServiceReferenceWS.UpdateUsuarioResponse> UpdateUsuarioAsync(Fomularios.ServiceReferenceWS.UpdateUsuarioRequest request);
        
        // CODEGEN: Generating message contract since element name ListUsuariosResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListUsuarios", ReplyAction="*")]
        Fomularios.ServiceReferenceWS.ListUsuariosResponse ListUsuarios(Fomularios.ServiceReferenceWS.ListUsuariosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListUsuarios", ReplyAction="*")]
        System.Threading.Tasks.Task<Fomularios.ServiceReferenceWS.ListUsuariosResponse> ListUsuariosAsync(Fomularios.ServiceReferenceWS.ListUsuariosRequest request);
        
        // CODEGEN: Generating message contract since element name ListUsuarioResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListUsuario", ReplyAction="*")]
        Fomularios.ServiceReferenceWS.ListUsuarioResponse ListUsuario(Fomularios.ServiceReferenceWS.ListUsuarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListUsuario", ReplyAction="*")]
        System.Threading.Tasks.Task<Fomularios.ServiceReferenceWS.ListUsuarioResponse> ListUsuarioAsync(Fomularios.ServiceReferenceWS.ListUsuarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddRol", ReplyAction="*")]
        void AddRol(int idRol, int idUsu);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddRol", ReplyAction="*")]
        System.Threading.Tasks.Task AddRolAsync(int idRol, int idUsu);
        
        // CODEGEN: Generating message contract since element name ListRolResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListRol", ReplyAction="*")]
        Fomularios.ServiceReferenceWS.ListRolResponse ListRol(Fomularios.ServiceReferenceWS.ListRolRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListRol", ReplyAction="*")]
        System.Threading.Tasks.Task<Fomularios.ServiceReferenceWS.ListRolResponse> ListRolAsync(Fomularios.ServiceReferenceWS.ListRolRequest request);
        
        // CODEGEN: Generating message contract since element name ListRolesResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListRoles", ReplyAction="*")]
        Fomularios.ServiceReferenceWS.ListRolesResponse ListRoles(Fomularios.ServiceReferenceWS.ListRolesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListRoles", ReplyAction="*")]
        System.Threading.Tasks.Task<Fomularios.ServiceReferenceWS.ListRolesResponse> ListRolesAsync(Fomularios.ServiceReferenceWS.ListRolesRequest request);
        
        // CODEGEN: Generating message contract since element name nombre from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddClientes", ReplyAction="*")]
        Fomularios.ServiceReferenceWS.AddClientesResponse AddClientes(Fomularios.ServiceReferenceWS.AddClientesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddClientes", ReplyAction="*")]
        System.Threading.Tasks.Task<Fomularios.ServiceReferenceWS.AddClientesResponse> AddClientesAsync(Fomularios.ServiceReferenceWS.AddClientesRequest request);
        
        // CODEGEN: Generating message contract since element name ListClientesResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListClientes", ReplyAction="*")]
        Fomularios.ServiceReferenceWS.ListClientesResponse ListClientes(Fomularios.ServiceReferenceWS.ListClientesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListClientes", ReplyAction="*")]
        System.Threading.Tasks.Task<Fomularios.ServiceReferenceWS.ListClientesResponse> ListClientesAsync(Fomularios.ServiceReferenceWS.ListClientesRequest request);
        
        // CODEGEN: Generating message contract since element name clave from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddConfig", ReplyAction="*")]
        Fomularios.ServiceReferenceWS.AddConfigResponse AddConfig(Fomularios.ServiceReferenceWS.AddConfigRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddConfig", ReplyAction="*")]
        System.Threading.Tasks.Task<Fomularios.ServiceReferenceWS.AddConfigResponse> AddConfigAsync(Fomularios.ServiceReferenceWS.AddConfigRequest request);
        
        // CODEGEN: Generating message contract since element name ListConfigResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListConfig", ReplyAction="*")]
        Fomularios.ServiceReferenceWS.ListConfigResponse ListConfig(Fomularios.ServiceReferenceWS.ListConfigRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListConfig", ReplyAction="*")]
        System.Threading.Tasks.Task<Fomularios.ServiceReferenceWS.ListConfigResponse> ListConfigAsync(Fomularios.ServiceReferenceWS.ListConfigRequest request);
        
        // CODEGEN: Generating message contract since element name valor from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateConfig", ReplyAction="*")]
        Fomularios.ServiceReferenceWS.UpdateConfigResponse UpdateConfig(Fomularios.ServiceReferenceWS.UpdateConfigRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateConfig", ReplyAction="*")]
        System.Threading.Tasks.Task<Fomularios.ServiceReferenceWS.UpdateConfigResponse> UpdateConfigAsync(Fomularios.ServiceReferenceWS.UpdateConfigRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddUsuariosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddUsuarios", Namespace="http://tempuri.org/", Order=0)]
        public Fomularios.ServiceReferenceWS.AddUsuariosRequestBody Body;
        
        public AddUsuariosRequest() {
        }
        
        public AddUsuariosRequest(Fomularios.ServiceReferenceWS.AddUsuariosRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddUsuariosRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int idUsuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string nombre;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string usuario1;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string contrasena;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string correo;
        
        public AddUsuariosRequestBody() {
        }
        
        public AddUsuariosRequestBody(int idUsuario, string nombre, string usuario1, string contrasena, string correo) {
            this.idUsuario = idUsuario;
            this.nombre = nombre;
            this.usuario1 = usuario1;
            this.contrasena = contrasena;
            this.correo = correo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddUsuariosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddUsuariosResponse", Namespace="http://tempuri.org/", Order=0)]
        public Fomularios.ServiceReferenceWS.AddUsuariosResponseBody Body;
        
        public AddUsuariosResponse() {
        }
        
        public AddUsuariosResponse(Fomularios.ServiceReferenceWS.AddUsuariosResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class AddUsuariosResponseBody {
        
        public AddUsuariosResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateUsuarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateUsuario", Namespace="http://tempuri.org/", Order=0)]
        public Fomularios.ServiceReferenceWS.UpdateUsuarioRequestBody Body;
        
        public UpdateUsuarioRequest() {
        }
        
        public UpdateUsuarioRequest(Fomularios.ServiceReferenceWS.UpdateUsuarioRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateUsuarioRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int idUsuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string nombre;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string usuario1;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string contrasena;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string correo;
        
        public UpdateUsuarioRequestBody() {
        }
        
        public UpdateUsuarioRequestBody(int idUsuario, string nombre, string usuario1, string contrasena, string correo) {
            this.idUsuario = idUsuario;
            this.nombre = nombre;
            this.usuario1 = usuario1;
            this.contrasena = contrasena;
            this.correo = correo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateUsuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateUsuarioResponse", Namespace="http://tempuri.org/", Order=0)]
        public Fomularios.ServiceReferenceWS.UpdateUsuarioResponseBody Body;
        
        public UpdateUsuarioResponse() {
        }
        
        public UpdateUsuarioResponse(Fomularios.ServiceReferenceWS.UpdateUsuarioResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class UpdateUsuarioResponseBody {
        
        public UpdateUsuarioResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListUsuariosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListUsuarios", Namespace="http://tempuri.org/", Order=0)]
        public Fomularios.ServiceReferenceWS.ListUsuariosRequestBody Body;
        
        public ListUsuariosRequest() {
        }
        
        public ListUsuariosRequest(Fomularios.ServiceReferenceWS.ListUsuariosRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ListUsuariosRequestBody {
        
        public ListUsuariosRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListUsuariosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListUsuariosResponse", Namespace="http://tempuri.org/", Order=0)]
        public Fomularios.ServiceReferenceWS.ListUsuariosResponseBody Body;
        
        public ListUsuariosResponse() {
        }
        
        public ListUsuariosResponse(Fomularios.ServiceReferenceWS.ListUsuariosResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ListUsuariosResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Fomularios.ServiceReferenceWS.Usuario[] ListUsuariosResult;
        
        public ListUsuariosResponseBody() {
        }
        
        public ListUsuariosResponseBody(Fomularios.ServiceReferenceWS.Usuario[] ListUsuariosResult) {
            this.ListUsuariosResult = ListUsuariosResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListUsuarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListUsuario", Namespace="http://tempuri.org/", Order=0)]
        public Fomularios.ServiceReferenceWS.ListUsuarioRequestBody Body;
        
        public ListUsuarioRequest() {
        }
        
        public ListUsuarioRequest(Fomularios.ServiceReferenceWS.ListUsuarioRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ListUsuarioRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int idUsu;
        
        public ListUsuarioRequestBody() {
        }
        
        public ListUsuarioRequestBody(int idUsu) {
            this.idUsu = idUsu;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListUsuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListUsuarioResponse", Namespace="http://tempuri.org/", Order=0)]
        public Fomularios.ServiceReferenceWS.ListUsuarioResponseBody Body;
        
        public ListUsuarioResponse() {
        }
        
        public ListUsuarioResponse(Fomularios.ServiceReferenceWS.ListUsuarioResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ListUsuarioResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Fomularios.ServiceReferenceWS.Usuario ListUsuarioResult;
        
        public ListUsuarioResponseBody() {
        }
        
        public ListUsuarioResponseBody(Fomularios.ServiceReferenceWS.Usuario ListUsuarioResult) {
            this.ListUsuarioResult = ListUsuarioResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListRolRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListRol", Namespace="http://tempuri.org/", Order=0)]
        public Fomularios.ServiceReferenceWS.ListRolRequestBody Body;
        
        public ListRolRequest() {
        }
        
        public ListRolRequest(Fomularios.ServiceReferenceWS.ListRolRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ListRolRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int idUsu;
        
        public ListRolRequestBody() {
        }
        
        public ListRolRequestBody(int idUsu) {
            this.idUsu = idUsu;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListRolResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListRolResponse", Namespace="http://tempuri.org/", Order=0)]
        public Fomularios.ServiceReferenceWS.ListRolResponseBody Body;
        
        public ListRolResponse() {
        }
        
        public ListRolResponse(Fomularios.ServiceReferenceWS.ListRolResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ListRolResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Fomularios.ServiceReferenceWS.Roles[] ListRolResult;
        
        public ListRolResponseBody() {
        }
        
        public ListRolResponseBody(Fomularios.ServiceReferenceWS.Roles[] ListRolResult) {
            this.ListRolResult = ListRolResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListRolesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListRoles", Namespace="http://tempuri.org/", Order=0)]
        public Fomularios.ServiceReferenceWS.ListRolesRequestBody Body;
        
        public ListRolesRequest() {
        }
        
        public ListRolesRequest(Fomularios.ServiceReferenceWS.ListRolesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ListRolesRequestBody {
        
        public ListRolesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListRolesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListRolesResponse", Namespace="http://tempuri.org/", Order=0)]
        public Fomularios.ServiceReferenceWS.ListRolesResponseBody Body;
        
        public ListRolesResponse() {
        }
        
        public ListRolesResponse(Fomularios.ServiceReferenceWS.ListRolesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ListRolesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Fomularios.ServiceReferenceWS.Roles[] ListRolesResult;
        
        public ListRolesResponseBody() {
        }
        
        public ListRolesResponseBody(Fomularios.ServiceReferenceWS.Roles[] ListRolesResult) {
            this.ListRolesResult = ListRolesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddClientesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddClientes", Namespace="http://tempuri.org/", Order=0)]
        public Fomularios.ServiceReferenceWS.AddClientesRequestBody Body;
        
        public AddClientesRequest() {
        }
        
        public AddClientesRequest(Fomularios.ServiceReferenceWS.AddClientesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddClientesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nombre;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string carpeta;
        
        public AddClientesRequestBody() {
        }
        
        public AddClientesRequestBody(string nombre, string carpeta) {
            this.nombre = nombre;
            this.carpeta = carpeta;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddClientesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddClientesResponse", Namespace="http://tempuri.org/", Order=0)]
        public Fomularios.ServiceReferenceWS.AddClientesResponseBody Body;
        
        public AddClientesResponse() {
        }
        
        public AddClientesResponse(Fomularios.ServiceReferenceWS.AddClientesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class AddClientesResponseBody {
        
        public AddClientesResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListClientesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListClientes", Namespace="http://tempuri.org/", Order=0)]
        public Fomularios.ServiceReferenceWS.ListClientesRequestBody Body;
        
        public ListClientesRequest() {
        }
        
        public ListClientesRequest(Fomularios.ServiceReferenceWS.ListClientesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ListClientesRequestBody {
        
        public ListClientesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListClientesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListClientesResponse", Namespace="http://tempuri.org/", Order=0)]
        public Fomularios.ServiceReferenceWS.ListClientesResponseBody Body;
        
        public ListClientesResponse() {
        }
        
        public ListClientesResponse(Fomularios.ServiceReferenceWS.ListClientesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ListClientesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Fomularios.ServiceReferenceWS.Clientes[] ListClientesResult;
        
        public ListClientesResponseBody() {
        }
        
        public ListClientesResponseBody(Fomularios.ServiceReferenceWS.Clientes[] ListClientesResult) {
            this.ListClientesResult = ListClientesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddConfigRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddConfig", Namespace="http://tempuri.org/", Order=0)]
        public Fomularios.ServiceReferenceWS.AddConfigRequestBody Body;
        
        public AddConfigRequest() {
        }
        
        public AddConfigRequest(Fomularios.ServiceReferenceWS.AddConfigRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddConfigRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string clave;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string valor;
        
        public AddConfigRequestBody() {
        }
        
        public AddConfigRequestBody(string clave, string valor) {
            this.clave = clave;
            this.valor = valor;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddConfigResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddConfigResponse", Namespace="http://tempuri.org/", Order=0)]
        public Fomularios.ServiceReferenceWS.AddConfigResponseBody Body;
        
        public AddConfigResponse() {
        }
        
        public AddConfigResponse(Fomularios.ServiceReferenceWS.AddConfigResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class AddConfigResponseBody {
        
        public AddConfigResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListConfigRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListConfig", Namespace="http://tempuri.org/", Order=0)]
        public Fomularios.ServiceReferenceWS.ListConfigRequestBody Body;
        
        public ListConfigRequest() {
        }
        
        public ListConfigRequest(Fomularios.ServiceReferenceWS.ListConfigRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ListConfigRequestBody {
        
        public ListConfigRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListConfigResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListConfigResponse", Namespace="http://tempuri.org/", Order=0)]
        public Fomularios.ServiceReferenceWS.ListConfigResponseBody Body;
        
        public ListConfigResponse() {
        }
        
        public ListConfigResponse(Fomularios.ServiceReferenceWS.ListConfigResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ListConfigResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Fomularios.ServiceReferenceWS.Configuraciones[] ListConfigResult;
        
        public ListConfigResponseBody() {
        }
        
        public ListConfigResponseBody(Fomularios.ServiceReferenceWS.Configuraciones[] ListConfigResult) {
            this.ListConfigResult = ListConfigResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateConfigRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateConfig", Namespace="http://tempuri.org/", Order=0)]
        public Fomularios.ServiceReferenceWS.UpdateConfigRequestBody Body;
        
        public UpdateConfigRequest() {
        }
        
        public UpdateConfigRequest(Fomularios.ServiceReferenceWS.UpdateConfigRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateConfigRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int clave;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string valor;
        
        public UpdateConfigRequestBody() {
        }
        
        public UpdateConfigRequestBody(int clave, string valor) {
            this.clave = clave;
            this.valor = valor;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateConfigResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateConfigResponse", Namespace="http://tempuri.org/", Order=0)]
        public Fomularios.ServiceReferenceWS.UpdateConfigResponseBody Body;
        
        public UpdateConfigResponse() {
        }
        
        public UpdateConfigResponse(Fomularios.ServiceReferenceWS.UpdateConfigResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class UpdateConfigResponseBody {
        
        public UpdateConfigResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceSoapChannel : Fomularios.ServiceReferenceWS.WebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceSoapClient : System.ServiceModel.ClientBase<Fomularios.ServiceReferenceWS.WebServiceSoap>, Fomularios.ServiceReferenceWS.WebServiceSoap {
        
        public WebServiceSoapClient() {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Fomularios.ServiceReferenceWS.AddUsuariosResponse Fomularios.ServiceReferenceWS.WebServiceSoap.AddUsuarios(Fomularios.ServiceReferenceWS.AddUsuariosRequest request) {
            return base.Channel.AddUsuarios(request);
        }
        
        public void AddUsuarios(int idUsuario, string nombre, string usuario1, string contrasena, string correo) {
            Fomularios.ServiceReferenceWS.AddUsuariosRequest inValue = new Fomularios.ServiceReferenceWS.AddUsuariosRequest();
            inValue.Body = new Fomularios.ServiceReferenceWS.AddUsuariosRequestBody();
            inValue.Body.idUsuario = idUsuario;
            inValue.Body.nombre = nombre;
            inValue.Body.usuario1 = usuario1;
            inValue.Body.contrasena = contrasena;
            inValue.Body.correo = correo;
            Fomularios.ServiceReferenceWS.AddUsuariosResponse retVal = ((Fomularios.ServiceReferenceWS.WebServiceSoap)(this)).AddUsuarios(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Fomularios.ServiceReferenceWS.AddUsuariosResponse> Fomularios.ServiceReferenceWS.WebServiceSoap.AddUsuariosAsync(Fomularios.ServiceReferenceWS.AddUsuariosRequest request) {
            return base.Channel.AddUsuariosAsync(request);
        }
        
        public System.Threading.Tasks.Task<Fomularios.ServiceReferenceWS.AddUsuariosResponse> AddUsuariosAsync(int idUsuario, string nombre, string usuario1, string contrasena, string correo) {
            Fomularios.ServiceReferenceWS.AddUsuariosRequest inValue = new Fomularios.ServiceReferenceWS.AddUsuariosRequest();
            inValue.Body = new Fomularios.ServiceReferenceWS.AddUsuariosRequestBody();
            inValue.Body.idUsuario = idUsuario;
            inValue.Body.nombre = nombre;
            inValue.Body.usuario1 = usuario1;
            inValue.Body.contrasena = contrasena;
            inValue.Body.correo = correo;
            return ((Fomularios.ServiceReferenceWS.WebServiceSoap)(this)).AddUsuariosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Fomularios.ServiceReferenceWS.UpdateUsuarioResponse Fomularios.ServiceReferenceWS.WebServiceSoap.UpdateUsuario(Fomularios.ServiceReferenceWS.UpdateUsuarioRequest request) {
            return base.Channel.UpdateUsuario(request);
        }
        
        public void UpdateUsuario(int idUsuario, string nombre, string usuario1, string contrasena, string correo) {
            Fomularios.ServiceReferenceWS.UpdateUsuarioRequest inValue = new Fomularios.ServiceReferenceWS.UpdateUsuarioRequest();
            inValue.Body = new Fomularios.ServiceReferenceWS.UpdateUsuarioRequestBody();
            inValue.Body.idUsuario = idUsuario;
            inValue.Body.nombre = nombre;
            inValue.Body.usuario1 = usuario1;
            inValue.Body.contrasena = contrasena;
            inValue.Body.correo = correo;
            Fomularios.ServiceReferenceWS.UpdateUsuarioResponse retVal = ((Fomularios.ServiceReferenceWS.WebServiceSoap)(this)).UpdateUsuario(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Fomularios.ServiceReferenceWS.UpdateUsuarioResponse> Fomularios.ServiceReferenceWS.WebServiceSoap.UpdateUsuarioAsync(Fomularios.ServiceReferenceWS.UpdateUsuarioRequest request) {
            return base.Channel.UpdateUsuarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<Fomularios.ServiceReferenceWS.UpdateUsuarioResponse> UpdateUsuarioAsync(int idUsuario, string nombre, string usuario1, string contrasena, string correo) {
            Fomularios.ServiceReferenceWS.UpdateUsuarioRequest inValue = new Fomularios.ServiceReferenceWS.UpdateUsuarioRequest();
            inValue.Body = new Fomularios.ServiceReferenceWS.UpdateUsuarioRequestBody();
            inValue.Body.idUsuario = idUsuario;
            inValue.Body.nombre = nombre;
            inValue.Body.usuario1 = usuario1;
            inValue.Body.contrasena = contrasena;
            inValue.Body.correo = correo;
            return ((Fomularios.ServiceReferenceWS.WebServiceSoap)(this)).UpdateUsuarioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Fomularios.ServiceReferenceWS.ListUsuariosResponse Fomularios.ServiceReferenceWS.WebServiceSoap.ListUsuarios(Fomularios.ServiceReferenceWS.ListUsuariosRequest request) {
            return base.Channel.ListUsuarios(request);
        }
        
        public Fomularios.ServiceReferenceWS.Usuario[] ListUsuarios() {
            Fomularios.ServiceReferenceWS.ListUsuariosRequest inValue = new Fomularios.ServiceReferenceWS.ListUsuariosRequest();
            inValue.Body = new Fomularios.ServiceReferenceWS.ListUsuariosRequestBody();
            Fomularios.ServiceReferenceWS.ListUsuariosResponse retVal = ((Fomularios.ServiceReferenceWS.WebServiceSoap)(this)).ListUsuarios(inValue);
            return retVal.Body.ListUsuariosResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Fomularios.ServiceReferenceWS.ListUsuariosResponse> Fomularios.ServiceReferenceWS.WebServiceSoap.ListUsuariosAsync(Fomularios.ServiceReferenceWS.ListUsuariosRequest request) {
            return base.Channel.ListUsuariosAsync(request);
        }
        
        public System.Threading.Tasks.Task<Fomularios.ServiceReferenceWS.ListUsuariosResponse> ListUsuariosAsync() {
            Fomularios.ServiceReferenceWS.ListUsuariosRequest inValue = new Fomularios.ServiceReferenceWS.ListUsuariosRequest();
            inValue.Body = new Fomularios.ServiceReferenceWS.ListUsuariosRequestBody();
            return ((Fomularios.ServiceReferenceWS.WebServiceSoap)(this)).ListUsuariosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Fomularios.ServiceReferenceWS.ListUsuarioResponse Fomularios.ServiceReferenceWS.WebServiceSoap.ListUsuario(Fomularios.ServiceReferenceWS.ListUsuarioRequest request) {
            return base.Channel.ListUsuario(request);
        }
        
        public Fomularios.ServiceReferenceWS.Usuario ListUsuario(int idUsu) {
            Fomularios.ServiceReferenceWS.ListUsuarioRequest inValue = new Fomularios.ServiceReferenceWS.ListUsuarioRequest();
            inValue.Body = new Fomularios.ServiceReferenceWS.ListUsuarioRequestBody();
            inValue.Body.idUsu = idUsu;
            Fomularios.ServiceReferenceWS.ListUsuarioResponse retVal = ((Fomularios.ServiceReferenceWS.WebServiceSoap)(this)).ListUsuario(inValue);
            return retVal.Body.ListUsuarioResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Fomularios.ServiceReferenceWS.ListUsuarioResponse> Fomularios.ServiceReferenceWS.WebServiceSoap.ListUsuarioAsync(Fomularios.ServiceReferenceWS.ListUsuarioRequest request) {
            return base.Channel.ListUsuarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<Fomularios.ServiceReferenceWS.ListUsuarioResponse> ListUsuarioAsync(int idUsu) {
            Fomularios.ServiceReferenceWS.ListUsuarioRequest inValue = new Fomularios.ServiceReferenceWS.ListUsuarioRequest();
            inValue.Body = new Fomularios.ServiceReferenceWS.ListUsuarioRequestBody();
            inValue.Body.idUsu = idUsu;
            return ((Fomularios.ServiceReferenceWS.WebServiceSoap)(this)).ListUsuarioAsync(inValue);
        }
        
        public void AddRol(int idRol, int idUsu) {
            base.Channel.AddRol(idRol, idUsu);
        }
        
        public System.Threading.Tasks.Task AddRolAsync(int idRol, int idUsu) {
            return base.Channel.AddRolAsync(idRol, idUsu);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Fomularios.ServiceReferenceWS.ListRolResponse Fomularios.ServiceReferenceWS.WebServiceSoap.ListRol(Fomularios.ServiceReferenceWS.ListRolRequest request) {
            return base.Channel.ListRol(request);
        }
        
        public Fomularios.ServiceReferenceWS.Roles[] ListRol(int idUsu) {
            Fomularios.ServiceReferenceWS.ListRolRequest inValue = new Fomularios.ServiceReferenceWS.ListRolRequest();
            inValue.Body = new Fomularios.ServiceReferenceWS.ListRolRequestBody();
            inValue.Body.idUsu = idUsu;
            Fomularios.ServiceReferenceWS.ListRolResponse retVal = ((Fomularios.ServiceReferenceWS.WebServiceSoap)(this)).ListRol(inValue);
            return retVal.Body.ListRolResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Fomularios.ServiceReferenceWS.ListRolResponse> Fomularios.ServiceReferenceWS.WebServiceSoap.ListRolAsync(Fomularios.ServiceReferenceWS.ListRolRequest request) {
            return base.Channel.ListRolAsync(request);
        }
        
        public System.Threading.Tasks.Task<Fomularios.ServiceReferenceWS.ListRolResponse> ListRolAsync(int idUsu) {
            Fomularios.ServiceReferenceWS.ListRolRequest inValue = new Fomularios.ServiceReferenceWS.ListRolRequest();
            inValue.Body = new Fomularios.ServiceReferenceWS.ListRolRequestBody();
            inValue.Body.idUsu = idUsu;
            return ((Fomularios.ServiceReferenceWS.WebServiceSoap)(this)).ListRolAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Fomularios.ServiceReferenceWS.ListRolesResponse Fomularios.ServiceReferenceWS.WebServiceSoap.ListRoles(Fomularios.ServiceReferenceWS.ListRolesRequest request) {
            return base.Channel.ListRoles(request);
        }
        
        public Fomularios.ServiceReferenceWS.Roles[] ListRoles() {
            Fomularios.ServiceReferenceWS.ListRolesRequest inValue = new Fomularios.ServiceReferenceWS.ListRolesRequest();
            inValue.Body = new Fomularios.ServiceReferenceWS.ListRolesRequestBody();
            Fomularios.ServiceReferenceWS.ListRolesResponse retVal = ((Fomularios.ServiceReferenceWS.WebServiceSoap)(this)).ListRoles(inValue);
            return retVal.Body.ListRolesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Fomularios.ServiceReferenceWS.ListRolesResponse> Fomularios.ServiceReferenceWS.WebServiceSoap.ListRolesAsync(Fomularios.ServiceReferenceWS.ListRolesRequest request) {
            return base.Channel.ListRolesAsync(request);
        }
        
        public System.Threading.Tasks.Task<Fomularios.ServiceReferenceWS.ListRolesResponse> ListRolesAsync() {
            Fomularios.ServiceReferenceWS.ListRolesRequest inValue = new Fomularios.ServiceReferenceWS.ListRolesRequest();
            inValue.Body = new Fomularios.ServiceReferenceWS.ListRolesRequestBody();
            return ((Fomularios.ServiceReferenceWS.WebServiceSoap)(this)).ListRolesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Fomularios.ServiceReferenceWS.AddClientesResponse Fomularios.ServiceReferenceWS.WebServiceSoap.AddClientes(Fomularios.ServiceReferenceWS.AddClientesRequest request) {
            return base.Channel.AddClientes(request);
        }
        
        public void AddClientes(string nombre, string carpeta) {
            Fomularios.ServiceReferenceWS.AddClientesRequest inValue = new Fomularios.ServiceReferenceWS.AddClientesRequest();
            inValue.Body = new Fomularios.ServiceReferenceWS.AddClientesRequestBody();
            inValue.Body.nombre = nombre;
            inValue.Body.carpeta = carpeta;
            Fomularios.ServiceReferenceWS.AddClientesResponse retVal = ((Fomularios.ServiceReferenceWS.WebServiceSoap)(this)).AddClientes(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Fomularios.ServiceReferenceWS.AddClientesResponse> Fomularios.ServiceReferenceWS.WebServiceSoap.AddClientesAsync(Fomularios.ServiceReferenceWS.AddClientesRequest request) {
            return base.Channel.AddClientesAsync(request);
        }
        
        public System.Threading.Tasks.Task<Fomularios.ServiceReferenceWS.AddClientesResponse> AddClientesAsync(string nombre, string carpeta) {
            Fomularios.ServiceReferenceWS.AddClientesRequest inValue = new Fomularios.ServiceReferenceWS.AddClientesRequest();
            inValue.Body = new Fomularios.ServiceReferenceWS.AddClientesRequestBody();
            inValue.Body.nombre = nombre;
            inValue.Body.carpeta = carpeta;
            return ((Fomularios.ServiceReferenceWS.WebServiceSoap)(this)).AddClientesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Fomularios.ServiceReferenceWS.ListClientesResponse Fomularios.ServiceReferenceWS.WebServiceSoap.ListClientes(Fomularios.ServiceReferenceWS.ListClientesRequest request) {
            return base.Channel.ListClientes(request);
        }
        
        public Fomularios.ServiceReferenceWS.Clientes[] ListClientes() {
            Fomularios.ServiceReferenceWS.ListClientesRequest inValue = new Fomularios.ServiceReferenceWS.ListClientesRequest();
            inValue.Body = new Fomularios.ServiceReferenceWS.ListClientesRequestBody();
            Fomularios.ServiceReferenceWS.ListClientesResponse retVal = ((Fomularios.ServiceReferenceWS.WebServiceSoap)(this)).ListClientes(inValue);
            return retVal.Body.ListClientesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Fomularios.ServiceReferenceWS.ListClientesResponse> Fomularios.ServiceReferenceWS.WebServiceSoap.ListClientesAsync(Fomularios.ServiceReferenceWS.ListClientesRequest request) {
            return base.Channel.ListClientesAsync(request);
        }
        
        public System.Threading.Tasks.Task<Fomularios.ServiceReferenceWS.ListClientesResponse> ListClientesAsync() {
            Fomularios.ServiceReferenceWS.ListClientesRequest inValue = new Fomularios.ServiceReferenceWS.ListClientesRequest();
            inValue.Body = new Fomularios.ServiceReferenceWS.ListClientesRequestBody();
            return ((Fomularios.ServiceReferenceWS.WebServiceSoap)(this)).ListClientesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Fomularios.ServiceReferenceWS.AddConfigResponse Fomularios.ServiceReferenceWS.WebServiceSoap.AddConfig(Fomularios.ServiceReferenceWS.AddConfigRequest request) {
            return base.Channel.AddConfig(request);
        }
        
        public void AddConfig(string clave, string valor) {
            Fomularios.ServiceReferenceWS.AddConfigRequest inValue = new Fomularios.ServiceReferenceWS.AddConfigRequest();
            inValue.Body = new Fomularios.ServiceReferenceWS.AddConfigRequestBody();
            inValue.Body.clave = clave;
            inValue.Body.valor = valor;
            Fomularios.ServiceReferenceWS.AddConfigResponse retVal = ((Fomularios.ServiceReferenceWS.WebServiceSoap)(this)).AddConfig(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Fomularios.ServiceReferenceWS.AddConfigResponse> Fomularios.ServiceReferenceWS.WebServiceSoap.AddConfigAsync(Fomularios.ServiceReferenceWS.AddConfigRequest request) {
            return base.Channel.AddConfigAsync(request);
        }
        
        public System.Threading.Tasks.Task<Fomularios.ServiceReferenceWS.AddConfigResponse> AddConfigAsync(string clave, string valor) {
            Fomularios.ServiceReferenceWS.AddConfigRequest inValue = new Fomularios.ServiceReferenceWS.AddConfigRequest();
            inValue.Body = new Fomularios.ServiceReferenceWS.AddConfigRequestBody();
            inValue.Body.clave = clave;
            inValue.Body.valor = valor;
            return ((Fomularios.ServiceReferenceWS.WebServiceSoap)(this)).AddConfigAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Fomularios.ServiceReferenceWS.ListConfigResponse Fomularios.ServiceReferenceWS.WebServiceSoap.ListConfig(Fomularios.ServiceReferenceWS.ListConfigRequest request) {
            return base.Channel.ListConfig(request);
        }
        
        public Fomularios.ServiceReferenceWS.Configuraciones[] ListConfig() {
            Fomularios.ServiceReferenceWS.ListConfigRequest inValue = new Fomularios.ServiceReferenceWS.ListConfigRequest();
            inValue.Body = new Fomularios.ServiceReferenceWS.ListConfigRequestBody();
            Fomularios.ServiceReferenceWS.ListConfigResponse retVal = ((Fomularios.ServiceReferenceWS.WebServiceSoap)(this)).ListConfig(inValue);
            return retVal.Body.ListConfigResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Fomularios.ServiceReferenceWS.ListConfigResponse> Fomularios.ServiceReferenceWS.WebServiceSoap.ListConfigAsync(Fomularios.ServiceReferenceWS.ListConfigRequest request) {
            return base.Channel.ListConfigAsync(request);
        }
        
        public System.Threading.Tasks.Task<Fomularios.ServiceReferenceWS.ListConfigResponse> ListConfigAsync() {
            Fomularios.ServiceReferenceWS.ListConfigRequest inValue = new Fomularios.ServiceReferenceWS.ListConfigRequest();
            inValue.Body = new Fomularios.ServiceReferenceWS.ListConfigRequestBody();
            return ((Fomularios.ServiceReferenceWS.WebServiceSoap)(this)).ListConfigAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Fomularios.ServiceReferenceWS.UpdateConfigResponse Fomularios.ServiceReferenceWS.WebServiceSoap.UpdateConfig(Fomularios.ServiceReferenceWS.UpdateConfigRequest request) {
            return base.Channel.UpdateConfig(request);
        }
        
        public void UpdateConfig(int clave, string valor) {
            Fomularios.ServiceReferenceWS.UpdateConfigRequest inValue = new Fomularios.ServiceReferenceWS.UpdateConfigRequest();
            inValue.Body = new Fomularios.ServiceReferenceWS.UpdateConfigRequestBody();
            inValue.Body.clave = clave;
            inValue.Body.valor = valor;
            Fomularios.ServiceReferenceWS.UpdateConfigResponse retVal = ((Fomularios.ServiceReferenceWS.WebServiceSoap)(this)).UpdateConfig(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Fomularios.ServiceReferenceWS.UpdateConfigResponse> Fomularios.ServiceReferenceWS.WebServiceSoap.UpdateConfigAsync(Fomularios.ServiceReferenceWS.UpdateConfigRequest request) {
            return base.Channel.UpdateConfigAsync(request);
        }
        
        public System.Threading.Tasks.Task<Fomularios.ServiceReferenceWS.UpdateConfigResponse> UpdateConfigAsync(int clave, string valor) {
            Fomularios.ServiceReferenceWS.UpdateConfigRequest inValue = new Fomularios.ServiceReferenceWS.UpdateConfigRequest();
            inValue.Body = new Fomularios.ServiceReferenceWS.UpdateConfigRequestBody();
            inValue.Body.clave = clave;
            inValue.Body.valor = valor;
            return ((Fomularios.ServiceReferenceWS.WebServiceSoap)(this)).UpdateConfigAsync(inValue);
        }
    }
}
